document.getElementById('heroImg').src=IMGS.balloon;
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function gmaps(q){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q)}
function dir(o,d){return 'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(o)+'&destination='+encodeURIComponent(d)+'&travelmode=driving'}
function statusInfo(code){return {booked:['✓ 已订','booked'],todo:['○ 待购票','todo'],onsite:['△ 现场购买','onsite'],free:['— 免费','free']}[code]||null}
function loadStatus(key,initial){return localStorage.getItem('trip-status-'+key)||initial}
function cycleStatus(btn){const key=btn.dataset.key;const order=['todo','booked','onsite','free'];const cur=btn.dataset.status;const nxt=order[(order.indexOf(cur)+1)%order.length];localStorage.setItem('trip-status-'+key,nxt);applyStatus(btn,nxt);toast('购票状态已更新')}
function applyStatus(btn,code){const [label,cls]=statusInfo(code);btn.className='status '+cls;btn.textContent=label;btn.dataset.status=code}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');clearTimeout(window._to);window._to=setTimeout(()=>el.classList.remove('show'),1600)}
const fd=document.getElementById('flightDeck');
FLIGHTS.forEach((f,i)=>fd.insertAdjacentHTML('beforeend',`<article class="flight"><div class="flight-top"><span>${esc(f.date)} · ${esc(f.tag)}</span><span>${String(i+1).padStart(2,'0')} / ${String(FLIGHTS.length).padStart(2,'0')}</span></div><div class="airports"><div class="airport"><b>${esc(f.from)}</b><span>${esc(f.depart)}</span></div><div class="plane-line"></div><div class="airport"><b>${esc(f.to)}</b><span>${esc(f.arrive)}</span></div></div><div class="flight-meta"><div><b>${esc(f.airline)}</b>${esc(f.no)}</div><div><b>${esc(f.duration)}</b>Flight time</div></div><div class="flight-note">${esc(f.note)}</div></article>`));
const list=document.getElementById('daysList');
DAYS.forEach(d=>{
 let body=`<div class="day-meta"><div class="meta-card"><b>今日移动</b>${esc(d.km)}</div><div class="meta-card"><b>Tonight</b>${esc(d.hotel)}</div></div><div class="timeline">`;
 d.events.forEach((e,ei)=>{const [time,title,type,imgKey,mapQ,ticket,note]=e;let status='';let ticketBtn='';if(ticket){const init=loadStatus(`${d.id}-${ei}`,ticket[0]);const si=statusInfo(init);status=`<button class="status ${si[1]}" data-key="${d.id}-${ei}" data-status="${init}" onclick="cycleStatus(this)">${si[0]}</button>`;if(ticket[1])ticketBtn=`<a class="btn clay" href="${ticket[1]}" target="_blank">购票 / 信息 ↗</a>`}let mapBtns='';if(mapQ){const mapId=`map-${d.id}-${ei}`;mapBtns=`<button class="btn" onclick="toggleMiniMap('${mapId}','${encodeURIComponent(mapQ)}')">Google 地图</button><a class="btn" href="${gmaps(mapQ)}" target="_blank">打开 Maps ↗</a>`}body+=`<div class="event ${esc(type)}"><div class="event-time">${esc(time)}</div><div class="dot"></div><div><h4>${esc(title)}</h4>${imgKey?`<img class="spot-img" src="${IMGS[imgKey]}" alt="${esc(title)}" loading="lazy">`:''}<p>${esc(note||'')}</p><div class="actions">${status}${ticketBtn}${mapBtns}</div>${mapQ?`<div class="mini-map" id="map-${d.id}-${ei}"></div>`:''}</div></div>`});
 body+='</div>';
 if(d.drives&&d.drives.length)body+=`<div class="drive-box"><h4>🚗 当日分段导航</h4>${d.drives.map(x=>`<div class="drive-row"><span><b>${esc(x[0])}</b> → ${esc(x[1])}</span><a class="btn" href="${dir(x[2],x[3])}" target="_blank">开始导航 ↗</a></div>`).join('')}</div>`;
 const r=RESTAURANTS[d.id];
 body+=`<div class="eat"><img src="${r.img}" alt="${esc(r.name)}" loading="lazy"><div class="eat-content"><div class="eat-label">Eat here · Route pick</div><h4>${esc(r.name)}</h4><div class="rating">★ ${esc(r.rating)} · ${esc(r.area)}</div><p>${esc(r.why)}<br><b>建议尝试：</b>${esc(r.food)}</p><div class="actions"><a class="btn" href="${gmaps(r.name+' '+r.area)}" target="_blank">Google Maps ↗</a></div></div></div>`;
 if(d.hotel&&d.hotel!=='—')body+=`<div class="stay-card">${d.hotelImg?`<img src="${IMGS[d.hotelImg]}" alt="${esc(d.hotel)}" loading="lazy">`:''}<div class="stay-content"><div class="stay-label">Tonight stay</div><h4>${esc(d.hotel.split(' · ')[0])}</h4><p>${esc(d.hotel)}</p><div class="actions"><a class="btn" href="${gmaps(d.hotel)}" target="_blank">酒店地图 ↗</a></div></div></div>`;
 list.insertAdjacentHTML('beforeend',`<article class="day" id="${d.id}"><button class="day-summary" onclick="toggleDay(this)"><div class="day-index">${d.id}</div><div><div class="day-date">${esc(d.date)}</div><h3>${esc(d.city)}</h3><p>${esc(d.summary)}</p></div><div class="chev">＋</div></button><div class="day-body">${body}</div></article>`)
});
function toggleDay(btn){const d=btn.closest('.day');d.classList.toggle('open');if(d.classList.contains('open'))setTimeout(()=>d.scrollIntoView({behavior:'smooth',block:'start'}),100)}
function toggleMiniMap(id,q){const box=document.getElementById(id);box.classList.toggle('show');if(box.classList.contains('show')&&!box.dataset.loaded){box.innerHTML=`<iframe loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q=${q}&output=embed"></iframe>`;box.dataset.loaded='1'}}
const DEFAULT_BUDGET=[['国际往返机票',5969],['土耳其内飞',900],['租车',2259],['油费 + 高速',875],['住宿',3000],['餐饮',1950],['景点门票',1170],['热气球',1400],['娱乐',1000]];
let budgetData=(()=>{try{const s=JSON.parse(localStorage.getItem('trip-budget-v1'));return Array.isArray(s)&&s.length?s:DEFAULT_BUDGET.map(x=>[x[0],x[1]])}catch(e){return DEFAULT_BUDGET.map(x=>[x[0],x[1]])}})();
function saveBudget(){localStorage.setItem('trip-budget-v1',JSON.stringify(budgetData))}
function renderBudget(){const max=Math.max(...budgetData.map(x=>Number(x[1])||0),1);const per=budgetData.reduce((s,x)=>s+(Number(x[1])||0),0);document.getElementById('budgetTotal').textContent='¥'+(per*2).toLocaleString();document.getElementById('budgetPerPerson').textContent='≈ ¥'+per.toLocaleString()+' / person';document.getElementById('budgetRows').innerHTML=budgetData.map(([n,v],i)=>`<div class="budget-row"><div class="budget-label"><span class="budget-name">${esc(n)}</span><span class="budget-value">¥${Number(v).toLocaleString()} /人 <button class="edit-budget" onclick="editBudgetItem(${i})">✎</button></span></div><div class="bar"><i style="width:${Math.max(5,(Number(v)||0)/max*100)}%"></i></div></div>`).join('')}
function toggleBudgetEditor(force){const box=document.getElementById('budgetEditor');const show=typeof force==='boolean'?force:!box.classList.contains('show');box.classList.toggle('show',show);if(show)setTimeout(()=>document.getElementById('budgetName').focus(),50)}
function addBudgetItem(){const name=document.getElementById('budgetName').value.trim();const amount=Number(document.getElementById('budgetAmount').value);if(!name||!Number.isFinite(amount)||amount<0){toast('请输入预算项目和金额');return}budgetData.push([name,Math.round(amount)]);saveBudget();renderBudget();document.getElementById('budgetName').value='';document.getElementById('budgetAmount').value='';toggleBudgetEditor(false);toast('预算已增加')}
function editBudgetItem(i){const cur=budgetData[i];const nv=prompt('修改「'+cur[0]+'」的每人预算（¥）',cur[1]);if(nv===null)return;const amount=Number(nv);if(!Number.isFinite(amount)||amount<0){toast('金额格式不正确');return}budgetData[i][1]=Math.round(amount);saveBudget();renderBudget();toast('预算已更新')}
function resetBudget(){if(!confirm('恢复初始预算？你新增和修改的预算会被清除。'))return;budgetData=DEFAULT_BUDGET.map(x=>[x[0],x[1]]);saveBudget();renderBudget();toast('已恢复初始预算')}
renderBudget();
