document.getElementById('heroImg').src=IMGS.balloon;
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function gmaps(q){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q)}
function dir(o,d){return 'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(o)+'&destination='+encodeURIComponent(d)+'&travelmode=driving'}
function statusInfo(code){return {booked:['✓ 已订','booked'],todo:['○ 待购票','todo'],onsite:['△ 现场购买','onsite'],free:['— 免费','free']}[code]||null}
function loadStatus(key, initial){return localStorage.getItem('trip-status-'+key)||initial}
function cycleStatus(btn){const key=btn.dataset.key;const order=['todo','booked','onsite','free'];let cur=btn.dataset.status;let nxt=order[(order.indexOf(cur)+1)%order.length];localStorage.setItem('trip-status-'+key,nxt);applyStatus(btn,nxt);toast('购票状态已更新')}
function applyStatus(btn,code){let [label,cls]=statusInfo(code);btn.className='status '+cls;btn.textContent=label;btn.dataset.status=code}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');clearTimeout(window._to);window._to=setTimeout(()=>el.classList.remove('show'),1600)}
const fd=document.getElementById('flightDeck');
FLIGHTS.forEach((f,i)=>{fd.insertAdjacentHTML('beforeend',`<article class="flight"><div class="flight-top"><span>${esc(f.date)} · ${esc(f.tag)}</span><span>${String(i+1).padStart(2,'0')} / ${String(FLIGHTS.length).padStart(2,'0')}</span></div><div class="airports"><div class="airport"><b>${esc(f.from)}</b><span>${esc(f.depart)}</span></div><div class="plane-line"></div><div class="airport"><b>${esc(f.to)}</b><span>${esc(f.arrive)}</span></div></div><div class="flight-meta"><div><b>${esc(f.airline)}</b>${esc(f.no)}</div><div><b>${esc(f.duration)}</b>Flight time</div></div><div class="flight-note">${esc(f.note)}</div></article>`)});
const list=document.getElementById('daysList');
DAYS.forEach((d)=>{
 let body=`<div class="day-meta"><div class="meta-card"><b>今日移动</b>${esc(d.km)}</div><div class="meta-card"><b>Tonight</b>${esc(d.hotel)}</div>${d.hotelImg?`<img class="hotel-img" src="${IMGS[d.hotelImg]}" alt="hotel" style="grid-column:1/-1">`:''}</div><div class="timeline">`;
 d.events.forEach((e,ei)=>{const [time,title,type,imgKey,mapQ,ticket,note]=e;let status='';let ticketBtn='';if(ticket){let init=loadStatus(`${d.id}-${ei}`,ticket[0]);let si=statusInfo(init);status=`<button class="status ${si[1]}" data-key="${d.id}-${ei}" data-status="${init}" onclick="cycleStatus(this)">${si[0]}</button>`;if(ticket[1])ticketBtn=`<a class="btn clay" href="${ticket[1]}" target="_blank">购票 / 信息 ↗</a>`}let mapBtns='';if(mapQ){const mapId=`map-${d.id}-${ei}`;mapBtns=`<button class="btn" onclick="toggleMiniMap('${mapId}','${encodeURIComponent(mapQ)}')">Google 地图</button><a class="btn" href="${gmaps(mapQ)}" target="_blank">打开 Maps ↗</a>`}body+=`<div class="event ${esc(type)}"><div class="event-time">${esc(time)}</div><div class="dot"></div><div><h4>${esc(title)}</h4>${imgKey?`<img class="spot-img" src="${IMGS[imgKey]}" alt="${esc(title)}">`:''}<p>${esc(note||'')}</p><div class="actions">${status}${ticketBtn}${mapBtns}</div>${mapQ?`<div class="mini-map" id="map-${d.id}-${ei}"></div>`:''}</div></div>`});
 body+='</div>';
 if(d.drives&&d.drives.length){body+=`<div class="drive-box"><h4>🚗 当日分段导航</h4>`+d.drives.map(x=>`<div class="drive-row"><span><b>${esc(x[0])}</b> → ${esc(x[1])}</span><a class="btn" href="${dir(x[2],x[3])}" target="_blank">开始导航 ↗</a></div>`).join('')+`</div>`}
 const r=RESTAURANTS[d.id];body+=`<div class="eat"><img src="${r.img}" alt="美食参考图"><div class="eat-content"><div class="eat-label">Eat here · 美食参考图</div><h4>${esc(r.name)}</h4><div class="rating">★ ${esc(r.rating)} · ${esc(r.area)}</div><p>${esc(r.why)}<br><b>建议尝试：</b>${esc(r.food)}</p><div class="actions"><a class="btn" href="${gmaps(r.name+' '+r.area)}" target="_blank">Google Maps ↗</a></div></div></div>`;
 list.insertAdjacentHTML('beforeend',`<article class="day" id="${d.id}"><button class="day-summary" onclick="toggleDay(this)"><div class="day-index">${d.id}</div><div><div class="day-date">${esc(d.date)}</div><h3>${esc(d.city)}</h3><p>${esc(d.summary)}</p></div><div class="chev">＋</div></button><div class="day-body">${body}</div></article>`)
});
function toggleDay(btn){const d=btn.closest('.day');d.classList.toggle('open');if(d.classList.contains('open')){setTimeout(()=>d.scrollIntoView({behavior:'smooth',block:'start'}),100)}}
function toggleMiniMap(id,q){const box=document.getElementById(id);box.classList.toggle('show');if(box.classList.contains('show')&&!box.dataset.loaded){box.innerHTML=`<iframe loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q=${q}&output=embed"></iframe>`;box.dataset.loaded='1'}}
const budget=[['国际往返机票',5969],['土耳其内飞',900],['租车',2259],['油费 + 高速',875],['住宿',3000],['餐饮',1950],['景点门票',1170],['热气球',1400],['娱乐',1000]];const max=Math.max(...budget.map(x=>x[1]));document.getElementById('budgetRows').innerHTML=budget.map(([n,v])=>`<div class="budget-row"><div class="budget-label"><span>${n}</span><span>¥${v.toLocaleString()} /人</span></div><div class="bar"><i style="width:${Math.max(5,v/max*100)}%"></i></div></div>`).join('');
let map,layers=[];const pts={IST:[41.2753,28.7519],SAW:[40.8986,29.3092],ASR:[38.7704,35.4954],Goreme:[38.6431,34.8289],Derinkuyu:[38.3737,34.734],Ihlara:[38.255,34.302],Selime:[38.303,34.259],Antalya:[36.8969,30.7133],Kaputas:[36.228,29.451],Kas:[36.2018,29.6377],Oludeniz:[36.549,29.115],Pamukkale:[37.9205,29.121],Ephesus:[37.939,27.341],ADB:[38.2924,27.157],HKG:[22.308,113.9185],BKK:[13.69,100.7501],MCT:[23.5933,58.2844],CGK:[-6.1256,106.6559]};
function initMap(){if(!window.L){document.getElementById('journeyMap').innerHTML='<div style="padding:20px;font-size:12px">地图组件需要联网加载。景点与导航按钮仍可正常使用。</div>';return}map=L.map('journeyMap',{zoomControl:true,scrollWheelZoom:false});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);renderMap('turkey')}
function clearLayers(){layers.forEach(l=>map.removeLayer(l));layers=[]}
function marker(name,p){let m=L.circleMarker(p,{radius:6,color:'#fbfaf6',weight:2,fillColor:'#24483b',fillOpacity:1}).addTo(map).bindPopup(`<b>${name}</b>`);layers.push(m)}
function line(names,color,dash){let l=L.polyline(names.map(n=>pts[n]),{color,weight:3,dashArray:dash||null,opacity:.88}).addTo(map);layers.push(l)}
function renderMap(mode){if(!map)return;clearLayers();if(mode==='turkey'){line(['ASR','Goreme','Derinkuyu','Ihlara','Selime','Goreme','Antalya','Kaputas','Kas','Oludeniz','Pamukkale','Ephesus','ADB'],'#356e79');line(['SAW','ASR'],'#a8563c','8,8');line(['ADB','IST'],'#a8563c','8,8');['SAW','ASR','Goreme','Antalya','Kaputas','Kas','Oludeniz','Pamukkale','Ephesus','ADB','IST'].forEach(n=>marker(n,pts[n]));map.fitBounds(L.latLngBounds(Object.entries(pts).filter(([k])=>['SAW','ASR','Goreme','Antalya','Kaputas','Kas','Oludeniz','Pamukkale','Ephesus','ADB','IST'].includes(k)).map(x=>x[1])),{padding:[20,20]})}else{line(['HKG','BKK','MCT','IST'],'#a8563c','8,8');line(['SAW','ASR'],'#a8563c','8,8');line(['ADB','IST','MCT','CGK','HKG'],'#a8563c','8,8');line(['ASR','Goreme','Antalya','Kaputas','Kas','Oludeniz','Pamukkale','Ephesus','ADB'],'#356e79');['HKG','BKK','MCT','IST','SAW','ASR','Goreme','Antalya','Oludeniz','Pamukkale','Ephesus','ADB','CGK'].forEach(n=>marker(n,pts[n]));map.fitBounds(L.latLngBounds(['HKG','BKK','MCT','IST','ASR','ADB','CGK'].map(n=>pts[n])),{padding:[20,20]})}}
document.querySelectorAll('[data-mapmode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mapmode]').forEach(x=>x.classList.remove('on'));b.classList.add('on');renderMap(b.dataset.mapmode)});window.addEventListener('load',initMap);